### ISSUE TITLE
deploying does not deploy

### ISSUE THREAD

**Issue by hookercookerman** [ethereum/mix#240]
Problem
Cannot deploy 

Env
Private Net;  Just simple example contract; Deployment account fully loaded with eth

from all the documentation I can find on the web; there is no indication of how this magic is meant to work.

I click Deploy Scenerio logs just say "running deployment"

what magic is one missing thanks

**Comment by yann300** [comment]
hi
is the rpc server is enabled in eth (--rpc)?
please could you paste logs if you can

**Comment by Alex-van-der-Peet** [comment]
Running into this too, happy to provide logs but need some more guidance.

Without the rpc server the Deploy to Network dialog notifies the user of this, so yes, it is active.

Tried both testnet and main, neither gives any feedback / timeout information (> 15 minutes)

Edit: The core issue here is no feedback, turns out the problem was my wallet wasn't unlocked.

**Comment by hookercookerman** [comment]
Yep that's the one wallet not unlocked thanks
