### ISSUE TITLE
1.0.5 crashes on start-up (El Capitan)

### ISSUE THREAD

**Issue by mttkay** [ethereum/mix#320]
MacBook Pro Retina (Mid 2015 Edition), MacOS 10.11.5

Crash dump:
https://gist.github.com/mttkay/75739fd0b329722959c4160eccdd4427

**Comment by devops398** [comment]
same here (MacBook Pro Retina (Mid 2015 Edition), MacOS 10.11.5), also I finally made a build, but mix just shows up in my dock and nothing happens..

By the way, I got succeed in building from source only when I tried 'make -j2' (instead of j4 - my actual count of cores), if I try to build with 'make -j4 && make install', I get this old error:

```
external_prereqs='/usr/local/Cellar/qt5/5.6.1/lib/QtCore.framework/Versions/5/QtCore;/usr/local/Cellar/qt5/5.6.1/lib/QtGui.framework/Versions/5/QtGui;/usr/local/Cellar/qt5/5.6.1/lib/QtWidgets.framework/Versions/5/QtWidgets;/usr/local/lib/libsnappy.1.dylib;/usr/local/opt/dbus/lib/libdbus-1.3.dylib'

-- 
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/BundleUtilities.cmake:975 (message):
  error: verify_app failed
Call Stack (most recent call first):
  alethzero/alethzero/cmake_install.cmake:34 (verify_app)
  alethzero/cmake_install.cmake:33 (include)
  cmake_install.cmake:37 (include)

make: *** [install] Error 1
```

There was a comment in issues about it (https://github.com/ethereum/webthree-umbrella/issues/117#issuecomment-170744295), but 
`brew reinstall -s cryptopp` didn't help me.
Reinstalling of everything qt5, ethereum, homebrew didn't help too.

**Comment by yann300** [comment]
Really sorry but mix has been discontinued.
We are now focusing on remix ( https://github.com/ethereum/remix ) which will i hope soon provide the same level of functionality as mix. Remix is in the early stage (alpha version). it only provides VM debugging for now.
Remix has already been integrated with browser solidity ( https://ethereum.github.io/browser-solidity/#version=soljson-latest.js ). You can use it right now. 
But as remix is still alpha, i would not recommend to use it as a production tool. please wait for further announcements.
Thanks and i hope you will enjoy playing with remix! 
Feel free to join the gitter channel https://gitter.im/ethereum/remix and share your thoughts with us.
